### ISSUE TITLE
Edge connectors - 12 and 24 back paste issue

### ISSUE THREAD

**Issue by sjgray** [bwack/KU-14194HB-RevB-KiCad#1]
I tried using your 12 and 24 pin edge connector footprints in a project and I discovered a problem with the pins on the bottom of both parts. One pin on the bottom has a paste area and the others do not. this causes the pin to appear grey where all other pins are yellow on the 3D board view. Not sure if this affects the final board.

**Comment by bwack** [comment]
Hi. Sorry for the long time to reply.
Many boards have been produced from this design, and the edge connectors are fine. I think you can see in the gerber files that the bottom solder mask layer is correct.. wait paste area ? You mean like SMD paste ? I'll have a double check.. smd paste is not a layer that is used with this all thruhole board.

**Comment by bwack** [comment]
I see what you mean here. this layer is not used, but if it is a board you have smd components, and you are using a solderpaste stencil, or a manufacturer is assembling the board for you, then it is a problem.
PH
![Screenshot from 2020-09-12 13-09-59](https://user-images.githubusercontent.com/11380333/92994292-6d89c180-f4f9-11ea-880c-f008571919df.png)

You can edit the footprint like here, remove the items in the paste layer, then save. Then go back to the design and update the footprint. Here is only shown the bottom paste layer, the top paste layer has many items too.
![Screenshot from 2020-09-12 13-13-02](https://user-images.githubusercontent.com/11380333/92994371-e4bf5580-f4f9-11ea-96b3-e38fefafd3d7.png)

Thanks for pointing it out. I have always wondered why the 3D view looks weird on some of the pads.

**Comment by bwack** [comment]
I have changed to components now. removed solder paste. Moved solder mask from the pcb to the components. What remains is the edge cuts, those are not possible to move to the components, they have to drawn on the board.

![Screenshot from 2020-09-12 13-48-51](https://user-images.githubusercontent.com/11380333/92994973-6f568380-f4ff-11ea-8317-54fda2b6e307.png)

**Comment by bwack** [comment]
end result :-)

![Screenshot from 2020-09-12 20-32-14](https://user-images.githubusercontent.com/11380333/93002403-186ca080-f537-11ea-9056-8a0424388393.png)

**Comment by sjgray** [comment]
Looks good!
    On Saturday, September 12, 2020, 02:32:56 p.m. EDT, bwack <notifications@github.com> wrote:  
 
 


end result :-)
