### ISSUE TITLE
Solder mask issue?

### ISSUE THREAD

**Issue by rljacobson** [bwack/KU-14194HB-RevB-KiCad#2]
Hi! Awesome project. You inspired me to do the 250469 Rev. B board.

I had five boards manufactured using your gerbers and noticed something unusual about the solder mask around the slots for the modulator and RF shield. The mask doesn't come up to the copper pour leaving bare FR4 surrounding the slot. Here's a picture:
![IMG_7531](https://user-images.githubusercontent.com/1412598/103319902-77c8c080-4a01-11eb-8718-c9a6f2738cf9.jpg)

It appears that it is this way in the design files. 
<img width="323" alt="Screen Shot 2020-12-29 at 6 52 18 PM" src="https://user-images.githubusercontent.com/1412598/103321511-fde80580-4a07-11eb-9a3c-a733da58b1dd.png">
<img width="355" alt="Screen Shot 2020-12-29 at 6 52 50 PM" src="https://user-images.githubusercontent.com/1412598/103321512-fde80580-4a07-11eb-801b-825a6c8b8e7b.png">

In fact, according to the design files there *should* be an exposed bit around the border of the rest of the surrounding ground copper pour, and after a closer look I see them as well.

As far as I can tell it shouldn't affect anything, but maybe it would look nicer if the mask came all the way up to the copper.

Should the slots themselves be plated?

**Comment by bwack** [comment]
Hi! Thanks for the feedback. It is very cool that you are doing the same with the 250469! Recently I've taken over a sprintlayout project file of the 250407 and I'm continuing the work on it :) 
You are right, the solder mask does not come up to all the pads. It is then a question if I should change it, but since it is a replica I'll keep it this way.

The original board does not have plated through slots. When I produced the boards, the producer asked if I wanted plated slots, and I answered yes. I don't know if it is possible to specify this in the KiCad software.

For reference:
https://github.com/bwack/KU-14194HB-RevB-pictures

Hans

**Comment by rljacobson** [comment]
I agree that you should keep it if the original has the same feature.

> I don't know if it is possible to specify this in the KiCad software.

I don't believe so, except of course for a written comment on User.Comments.

I can't wait to see your 250407! Here is a preview of my 250469 Rev. B:

<img width="1282" alt="Screen Shot 2021-01-04 at 11 25 43 AM" src="https://user-images.githubusercontent.com/1412598/103556337-a28e9b00-4e7f-11eb-9531-910717152550.png">

The original board has a bunch of these geometric copper zones: ![](https://www.breadbox64.com/wp-content/uploads/2016/04/IMG_9784.jpg)

It is hard to deal with them, and they are not all just GND/PWR fills on either side. Worse, my reference pictures clearly show they are not computer drawn, as some have rounded over corners, irregularly angled lines, fills not filling the available space, etc. What's weird is that Rev. A *does* look like it was computer drawn, very neat and regular. So they relaxed a bit for Rev B.? Strange. Anyway, I don't see these on your KU board, I guess because of the density of the traces. But I can tell that the traces and these fills will make it a DRC nightmare.

**Comment by bwack** [comment]
Great work on the 250469.
Have you seen this ? http://www.c-64.org/de/mainboards.html unfortunately it does not have images of the pcb bottom side.
DRC is indeed very exhaustive :)

**Comment by rljacobson** [comment]
Yep, I have a lot of good reference photos. I need them especially because I don't own a C64 motherboard. It is mysterious to me how features in different photos can be so misaligned when they are identical in reality.
