### ISSUE TITLE
Someone changed the silkscreen and claimed your PCB as their own

### ISSUE THREAD

**Issue by xiphias256** [bwack/KU-14194HB-RevB-KiCad#3]
It came to my discovery on a Facebook group that someone took your PCB design, just changed the silkscreen and claiming it to be their own. Just want you to know what happened, if you where unaware.

https://retrotechlyfe.com/home/ols/products/commodore-64-8-bit-computer-motherboard-logic-board-premium-gold-immersed-traces-stellar-signal-integrity

Keep up the good work!!

**Comment by xiphias256** [comment]
After writing an email to the person responsible, he now at least give you credit. But no link to this github project.

**Comment by bwack** [comment]
Thanks!
