### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by fab1979** [bwack/KU-14194HB-RevB-KiCad#4]
![20210418_151051 1](https://user-images.githubusercontent.com/82777620/115157752-f4d38080-a058-11eb-9c51-2085126d0ca7.jpg)

![20210418_151025 1](https://user-images.githubusercontent.com/82777620/115157789-251b1f00-a059-11eb-8d7f-c9cd3cb57d08.jpg)
![20210418_151017 1](https://user-images.githubusercontent.com/82777620/115157811-395f1c00-a059-11eb-90d4-b4f5ced609d8.jpg)
Tried everything i could think of voltages look fine checked mos chips on a working machine. Im new to soldering and pcboards, i had a friend (electrical engineer) to see if he could figure out anything with no luck. Any info on what i could try would be very appreciated.

**Comment by Langwell** [comment]
Try a 330ohm resistor at R42

**Comment by fab1979** [comment]
You sir are the man Thank You
![20210420_160839 1](https://user-images.githubusercontent.com/82777620/115457782-ede07580-a1f2-11eb-8ddb-03c3b7777d65.jpg)

**Comment by fab1979** [comment]
Only issue is its not a steady image it flickers a little but it works.

**Comment by Langwell** [comment]
> Only issue is its not a steady image it flickers a little but it works.



> You sir are the man Thank You
> ![20210420_160839 1](https://user-images.githubusercontent.com/82777620/115457782-ede07580-a1f2-11eb-8ddb-03c3b7777d65.jpg)

Great to see you up and running, check on another TV, I've seen perfectly working C64 machines display perfectly on one TV and experience things like sudden brightness changes on others.  There is a helpful KU-14194 assembly thread on Forum64.de
