### ISSUE TITLE
File not checked into repo

### ISSUE THREAD

**Issue by weerligbytjie** [bwack/KU-14194HB-RevB-KiCad#5]
I tried to open the schematic and it is complaining that KU-14194HB-REV-B-KiCad-rescue.lib not being found.
Kicad then hangs.

**Comment by bwack** [comment]
Thanks! I've added and pushed the file to the repo.

**Comment by weerligbytjie** [comment]
Still asking for KU-14194HB-REV-B-KiCad-rescue.lib

**Comment by bwack** [comment]
$ git add KU-14194HB-REV-B-KiCad-rescue.lib
The following paths are ignored by one of your .gitignore files:
KU-14194HB-REV-B-KiCad-rescue.lib
Use -f if you really want to add them.

Ahh. my bad. Thanks for your patience :smile:
